export const TODOS_SEND_GET = 'TODOS_SEND_GET';
export const TODOS_SEND_GET_IS_SUCCESS = 'TODOS_SEND_GET_IS_SUCCESS';
export const TODOS_SEND_GET_IS_FAILURE = 'TODOS_SEND_GET_IS_FAILURE';

export const TODO_ADD = 'TODO_ADD';
export const TODO_SEND_CREATE = 'TODO_SEND_CREATE';
export const TODO_SEND_CREATE_IS_SUCCESS = 'TODO_SEND_CREATE_IS_SUCCESS';
export const TODO_SEND_CREATE_IS_FAILURE = 'TODO_SEND_CREATE_IS_FAILURE';

export const TODO_MODIFY = 'TODO_MODIFY';
export const TODO_SEND_UPDATE = 'TODO_SEND_UPDATE';
export const TODO_SEND_UPDATE_IS_SUCCESS = 'TODO_SEND_UPDATE_IS_SUCCESS';
export const TODO_SEND_UPDATE_IS_FAILURE = 'TODO_SEND_UPDATE_IS_FAILURE';

export const TODO_REMOVE = 'TODO_REMOVE';
export const TODO_SEND_DELETE = 'TODO_SEND_DELETE';
export const TODO_SEND_DELETE_IS_SUCCESS = 'TODO_SEND_DELETE_IS_SUCCESS';
export const TODO_SEND_DELETE_IS_FAILURE = 'TODO_SEND_DELETE_IS_FAILURE';

export const LOGIN_USER_SEND_CREATE = 'LOGIN_USER_SEND_CREATE'
export const LOGIN_USER_SEND_CREATE_IS_FAILURE = 'LOGIN_USER_SEND_CREATE_IS_FAILURE';
export const LOGIN_USER_SEND_CREATE_IS_SUCCESS = 'LOGIN_USER_SEND_CREATE_IS_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER'

export const USER_SEND_CREATE = 'USER_SEND_CREATE'

export const DEPARTMENTS_SEND_GET = 'DEPARTMENTS_SEND_GET';
export const DEPARTMENTS_SEND_GET_IS_SUCCESS = 'DEPARTMENTS_SEND_GET_IS_SUCCESS';
export const DEPARTMENTS_SEND_GET_IS_FAILURE = 'DEPARTMENTS_SEND_GET_IS_FAILURE';
