export const TODOS_SEND_GET_REQUEST = 'TODOS_SEND_GET_REQUEST';
export const TODOS_SEND_GET_REQUEST_SUCCESSFUL = 'TODOS_SEND_GET_REQUEST_SUCCESSFUL';
export const TODOS_SEND_GET_REQUEST_ERROR = 'TODOS_SEND_GET_REQUEST_ERROR';
