export const TODOS_SEND_GET = 'TODOS_SEND_GET';
export const TODOS_SEND_GET_IS_SUCCESS = 'TODOS_SEND_GET_IS_SUCCESS';
export const TODOS_SEND_GET_IS_FAILURE = 'TODOS_SEND_GET_IS_FAILURE';

export const TODO_SEND_CREATE = 'TODO_SEND_CREATE';
export const TODO_SEND_CREATE_IS_SUCCESS = 'TODO_SEND_CREATE_IS_SUCCESS';
export const TODO_SEND_CREATE_IS_FAILURE = 'TODO_SEND_CREATE_IS_FAILURE';

